# docker/Dockerfile.api
FROM python:3.11-slim
WORKDIR /app
COPY ./apps/api /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ENV DATABASE_URL=sqlite:///./recipes.db
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
