# FastAPI Backend Dockerfile

FROM python:3.11-slim

# Set work directory

WORKDIR /app

# Install dependencies

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app source code

COPY ./app ./app

# Expose API port

EXPOSE 8000

# Start FastAPI server

CMD ["uvicorn", "app.services.main:app", "--host", "0.0.0.0", "--port", "8000"]
