# Frontend React/Vite Dockerfile

FROM node:18-alpine AS build

# Set work directory

WORKDIR /web

# Install dependencies

COPY ./web/package*.json ./
RUN npm install

# Build production files

COPY ./web .
RUN npm run build

# Nginx stage

FROM nginx:alpine

# Copy build files

COPY --from=build /web/dist /usr/share/nginx/html

# Copy Nginx configuration

COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
