# docker/Dockerfile.web
FROM node:18-alpine
WORKDIR /usr/src/app
COPY ./apps/web/package.json ./apps/web/
COPY ./apps/web/yarn.lock? ./
RUN npm install
COPY ./apps/web/ ./
RUN npm run build
RUN npm install -g serve
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
